FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG CONSUMER
RUN CGO_ENABLED=0 GOOS=linux go build -o consumer ./cmd/consumers/${CONSUMER}

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/consumer .
CMD ["./consumer"]
