apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: link-generator
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        env:
        - name: CLICKHOUSE_DB
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLICKHOUSE_DB
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLICKHOUSE_USER
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLICKHOUSE_PASSWORD
        - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
          value: "1"
        ports:
        - containerPort: 8123
        - containerPort: 9000
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi
